version: '3.7'

# For connection urls to the following instances, see
# https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-wallet
    links:
      - postgres
    networks:
      - postgres_network
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.docker

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_wallet
    networks:
      - postgres_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
networks:
  postgres_network:
    driver: bridge

